services:
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:8080"
    environment:
      FLASK_ENV: development
    volumes:
      - ./data:/app/data  # Volume para o SQLite

volumes:
  db_data:
    driver: local
