services:
  app:
    image: joaokarpinski/app_prova_1_computacao_distribuida:latest
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:
      FLASK_ENV: development
    volumes:
      - ./data:/app/data  # Volume para o SQLite
    networks:
      - app_net

  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_net

networks:
  app_net:
    driver: bridge